In [10]:
import pandas as pd

In [11]:
df = pd.read_excel("../data/raw/Online_Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [12]:
print("*****Dimensions of the datasets*****",df.shape)
print("*****columns of the datasets*****",df.columns.tolist())

*****Dimensions of the datasets***** (541909, 8)
*****columns of the datasets***** ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 40.0+ MB

In [14]:
print("*****missing values in the datasets*****\n",df.isnull().sum())
print("*****duplicate values in the datasets*****\n",df.duplicated().sum())

*****missing values in the datasets*****
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
*****duplicate values in the datasets*****
 5268

In [15]:
duplicates = df[df.duplicated(keep=False)]
duplicates.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom

In [16]:
#delete duplicates
df_clean=df.drop_duplicates(keep='first').copy()
df_clean.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom

In [17]:
#negative values in quantity 
negative_quantity=df_clean[df_clean['Quantity']<0]
print("negative value in quantity",negative_quantity.shape)

negative value in quantity (10587, 8)

In [18]:
negative_quantity.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [19]:
begin_c=negative_quantity['InvoiceNo'].astype(str).str.startswith("C")
# astype(str)  : convertit en texte (certains numéros sont des nombres)
# str.startswith("C") : True si le numéro commence par C, sinon False
print("Avec 'C' (annulations) :", begin_c.sum())
print("Sans 'C' (à examiner) :", (~begin_c).sum())# ~ = inverse

Avec 'C' (annulations) : 9251
Sans 'C' (à examiner) : 1336

In [20]:
df_cancelled = df_clean[df_clean["InvoiceNo"].astype(str).str.startswith("C")].copy()
df_sales = df_clean[~df_clean["InvoiceNo"].astype(str).str.startswith("C")].copy()
print("Annulations :", len(df_cancelled))
print("Ventes :", len(df_sales))

Annulations : 9251
Ventes : 527390

In [21]:
zero_price=df_sales[df_sales['UnitPrice']==0]
print("Lignes avec prix = 0 :", zero_price.shape[0])
zero_price.head(10)

Lignes avec prix = 0 : 2510

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [22]:
df_sales=df_clean[
    (df_clean['Quantity']>0) &
    (df_clean['UnitPrice']>0) &
    (~df_clean["InvoiceNo"].astype(str).str.startswith("C"))
].copy()

print("Lignes avant :", len(df_clean))
print("Ventes propres :", len(df_sales))
print("Lignes exclues :", len(df_clean) - len(df_sales))
df_sales.head(20)

Lignes avant : 536641
Ventes propres : 524878
Lignes exclues : 11763

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom

In [23]:
df_rejected=df_clean[
    (df_clean['Quantity']<0) |
    (df_clean['UnitPrice']<=0) |
    (df_clean["InvoiceNo"].astype(str).str.startswith("C"))
].copy()

print("Annulations :", len(df_cancelled))
print("Lignes rejetées au total :", len(df_rejected))
print("Rejetées hors annulations :", len(df_rejected) - len(df_cancelled))

Annulations : 9251
Lignes rejetées au total : 11763
Rejetées hors annulations : 2512

In [24]:
# --- VALIDATION ---
print("Quantités <= 0 :", (df_sales["Quantity"] <= 0).sum())
print("Prix <= 0 :", (df_sales["UnitPrice"] <= 0).sum())
print("Factures 'C' :", df_sales["InvoiceNo"].astype(str).str.startswith("C").sum())
print("Doublons :", df_sales.duplicated().sum())

Quantités <= 0 : 0
Prix <= 0 : 0
Factures 'C' : 0
Doublons : 0

In [29]:
for d in (df_sales, df_cancelled, df_rejected):
    d["InvoiceNo"] = d["InvoiceNo"].astype(str)
    d["StockCode"] = d["StockCode"].astype(str)
for d in (df_rejected, df_cancelled):
    d["Description"] = d["Description"].astype("string")

In [30]:
df_sales.to_parquet("../data/silver_sales.parquet",  index=False)
df_rejected.to_parquet("../data/rejected_sales.parquet", index=False)
df_cancelled.to_parquet("../data/cancelled_sales.parquet", index=False)
print("fichiers sauvegardés dans le dossier data")

fichiers sauvegardés dans le dossier data

In [31]:
df_sales=pd.read_parquet("../data/silver_sales.parquet")
df_sales["Revenue"]=df_sales["Quantity"]*df_sales["UnitPrice"]
print("Chiffre d'affaires total :", round(df_sales["Revenue"].sum(), 2))
print("Nombre de commandes :", df_sales["InvoiceNo"].nunique())
print("Panier moyen :", round(df_sales.groupby("InvoiceNo")["Revenue"].sum().mean(), 2))

Chiffre d'affaires total : 10642110.8
Nombre de commandes : 19960
Panier moyen : 533.17

In [32]:
#gold CA par country
gold_country = (df_sales.groupby("Country")["Revenue"].sum().sort_values(ascending=False).reset_index())
gold_country.head(10)

          Country      Revenue
0  United Kingdom  9001744.094
1     Netherlands   285446.340
2            EIRE   283140.520
3         Germany   228678.400
4          France   209625.370
5       Australia   138453.810
6           Spain    61558.560
7     Switzerland    57067.600
8         Belgium    41196.340
9          Sweden    38367.830

In [33]:
#gold CA par description
gold_description=(df_sales.groupby("Description")["Revenue"].sum().sort_values(ascending=False).reset_index())
gold_description.head(10)

                          Description    Revenue
0                      DOTCOM POSTAGE  206248.77
1            REGENCY CAKESTAND 3 TIER  174156.54
2         PAPER CRAFT , LITTLE BIRDIE  168469.60
3  WHITE HANGING HEART T-LIGHT HOLDER  106236.72
4                       PARTY BUNTING   99445.23
5             JUMBO BAG RED RETROSPOT   94159.81
6      MEDIUM CERAMIC TOP STORAGE JAR   81700.92
7                             POSTAGE   78101.88
8                              Manual   77752.82
9                  RABBIT NIGHT LIGHT   66870.03

In [34]:
#gold CA par mois
gold_month=(df_sales.groupby(df_sales["InvoiceDate"].dt.to_period("M"))["Revenue"].sum().sort_values(ascending=False).reset_index())
gold_month.head(10)

  InvoiceDate      Revenue
0     2011-11  1503866.780
1     2011-10  1151263.730
2     2011-09  1056435.192
3     2010-12   821452.730
4     2011-05   769296.610
5     2011-06   760547.010
6     2011-08   757841.380
7     2011-07   718076.121
8     2011-03   716215.260
9     2011-01   689811.610

In [35]:
gold_country.to_parquet("../data/gold_country.parquet", index=False)
gold_description.to_parquet("../data/gold_description.parquet", index=False)
gold_month.to_parquet("../data/gold_month.parquet", index=False)
print("fichiers sauvegardés dans le dossier data")

fichiers sauvegardés dans le dossier data

In [36]:
orders_country = (
    df_sales.groupby("Country")["InvoiceNo"]
    .nunique()
    .sort_values(ascending=False)
    .reset_index()
)
orders_country.head(10)

          Country  InvoiceNo
0  United Kingdom      18019
1         Germany        457
2          France        392
3            EIRE        288
4         Belgium         98
5     Netherlands         94
6           Spain         90
7        Portugal         58
8       Australia         57
9     Switzerland         54

In [37]:
non_produits = ["DOTCOM POSTAGE", "POSTAGE", "Manual", "Discount", "CARRIAGE", "Bank Charges"]

gold_products = (
    df_sales[~df_sales["Description"].isin(non_produits)]
    .groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)
gold_products

                          Description    Revenue
0            REGENCY CAKESTAND 3 TIER  174156.54
1         PAPER CRAFT , LITTLE BIRDIE  168469.60
2  WHITE HANGING HEART T-LIGHT HOLDER  106236.72
3                       PARTY BUNTING   99445.23
4             JUMBO BAG RED RETROSPOT   94159.81
5      MEDIUM CERAMIC TOP STORAGE JAR   81700.92
6                  RABBIT NIGHT LIGHT   66870.03
7     PAPER CHAIN KIT 50'S CHRISTMAS    64875.59
8       ASSORTED COLOUR BIRD ORNAMENT   58927.62
9                       CHILLI LIGHTS   54096.36

In [38]:
gold_products.to_parquet("../data/gold_products.parquet", index=False)